name: fylgja
description: A Flutter app for monitoring network connectivity in the background
publish_to: 'none'

version: 1.0.24+81

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  flutter_background_service: ^5.0.5
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  flutter_local_notifications: ^17.2.2
  package_info_plus: ^8.0.0
  logger: ^2.0.2+1
  intl: ^0.19.0
  introduction_screen: ^3.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true
  
  assets:
    - assets/audio/
    - assets/about icon.png
    - assets/searchlogo.png

flutter_native_splash:
  color: "#FFFDE7"
  image: assets/searchlogo.png
  android_12:
    image: assets/searchlogo.png
    color: "#FFFDE7"
  android_gravity: center
  fullscreen: true
